version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    restart: always
    links:
      - redis:redis
    ports:
      - 18081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379

  mongo:
    container_name: mongo
    image: mongo:4.2-bionic
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: svpc4EJvz
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/configdb:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    hostname: mongo-express
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: svpc4EJvz
